phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing Node.js and npm...
      - curl -o nodejs.msi https://nodejs.org/dist/v20.11.0/node-v20.11.0-x64.msi
      - msiexec.exe /i nodejs.msi /quiet /norestart
      - echo Verifying installation...
      - set "PATH=%PATH%;C:\Program Files\nodejs"
      - node -v
      - npm -v
  pre_build:
    commands:
      - echo Preparing for build...
  build:
    commands:
      - echo Installing project dependencies...
      - npm install || { echo "Install failed"; exit 1; }
  post_build:
    commands:
      - echo Build completed successfully
      - if exist build\* (powershell Compress-Archive -Path 'build\*' -DestinationPath 'output.zip') else echo "Build directory does not exist."
artifacts:
  files:
    - output.zip
