version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js and npm...
      - curl -o nodejs.msi https://nodejs.org/dist/v20.11.0/node-v20.11.0-x64.msi
      - msiexec.exe /i nodejs.msi /quiet /norestart
      - echo Verifying installation...
      - setx PATH "%PATH%;C:\Program Files\nodejs"
      - node -v
      - npm -v
      - echo Installing project dependencies...
      - npm install

  pre_build:
    commands:
      - echo Preparing for build...

  build:
    commands:
      - echo Building the project...
      - npm run build

  post_build:
    commands:
      - echo Build completed successfully
      - echo Compressing build output...
      - powershell Compress-Archive -Path 'build\*' -DestinationPath 'output.zip'

artifacts:
  files:
    - output.zip
